theme = "solarized_dark"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"

[keys.normal]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
"C-e" = "scroll_down"
"C-y" = "scroll_up"

[keys.select]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
